---

- hosts: all
  become: true
  tasks:


  - name: check packages running
    command: docker --version && php --version
    register: result
    ignore_errors: yes


  - name: check mariadb
    command: mysql --version
    register: result
    ignore_errors: yes
