---

- hosts: all
  become: true
  pre_tasks:


  - name: update repo cache (Amazon)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:


  - name: add ssh key for david
    tags: always
    authorized_key:
        user: david
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7jbMMDjc8imeQ1TKSyvHKy8c0BUXtV9LPY+8EMNccZJ2PwC6hZkQkoYUvCNwzPtlCj+h+8VjSIiQcJpBMgho/8WiG/TVGSlNeVo4C3atTaWvn/cygxJr6TYaWO2HMwiFTraL3ywIaxKxb2o0vvCZ01uZRFFWTk5Lrpae4vsmR9JETLIxHurycOvApvdVoiM8E4ch1DHuy2nLmBMI2za1ajJ/CevnE1Bd4z/rrw4swMtZA6gWO3horxm5f0pZBbAaW74sXt2k2dhT2N5q1Ga+YmhyxKsGEenZxW5STc9JYi4wxE/iV/oQ0uLQ51q4WFVN9laTxLBGWQX84MsfhUknh"



- hosts: web_servers
  become: true
  tasks:


  - name: Install packages
    tags: apache,apache2,amazon,ubuntu,httpd
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
         - "{{ docker_package }}"
      state: latest

  - name: Start and enable apache and firewall
    tags: amazon,httpd,apache
    service: 
        name: httpd
        state: started
        enabled: yes
    when: ansible_distribution == "Amazon"

  - name: start and enable firewall
    tags: amazon,httpd,apache
    service: 
        name: firewalld
        state: started
        enabled: yes
    when: ansible_distribution == "Amazon"

  - name: open port 80
    tags: amazon,httpd,apache
    command: firewall-cmd --add-port=80/tcp
    when: ansible_distribution == "Amazon"

  - name: Reload firewall 
    tags: amazon,httpd,apache
    service:
        name: firewalld
    when: ansible_distribution == "Amazon"

 

  - name: copy coolsite html file for site
    tags: apache,apache2,httpd
    copy:
      src: coolsite.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu,amazon
    package:
       name: "{{ mariadb_package }}"
       state: latest


- hosts: file_servers
  become: true
  tasks: 

  - name: install samba package
    tags: samba,file
    package:
       name: samba
       state: latest
