---

- hosts: all
  become: true
  tasks:


  - name: Install packages
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
         - "{{ docker_package }}"
      state: latest
      update_cache: yes 

  - name: Start and enable apache and firewall
    service: 
        name: httpd
        state: started
        enabled: yes
    when: ansible_distribution == "Amazon"

  - name: start and enable firewall
    service: 
        name: firewalld
        state: started
        enabled: yes
    when: ansible_distribution == "Amazon"

  - name: open port 80
    command: firewall-cmd --add-port=80/tcp
    when: ansible_distribution == "Amazon"

  - name: Reload firewall 
    service:
        name: firewalld
    when: ansible_distribution == "Amazon"




