---

- hosts: all
  become: true
  tasks:


  - name: Remove packages
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
         - "{{ docker_package }}"
      state: absent
      update_cache: yes
      autoremove: yes
